= Sir.LOIN Sandbox Project 기여 가이드
// refs:
:link-prj: https://github.com/sirloin-dev/meatplatform-sandbox

== 행동 강령
이 프로젝트는 link:CODE_OF_CONDUCT.adoc[Sir.LOIN Sandbox Project 행동 강령] 원칙을 적용받습니다. 참여자 여러분들은 행동 강령을 준수해 주시기 바랍니다.

행동 강령 위반하는 여러 행위를 발견하신다면, 즉시 신고해주세요.

== Pull Request 제출 방법
아래 순서대로 진행해 주시기 바랍니다.

. link:{link-prj}/issues[Github Issues] 에 발견하신 문제를 issue 로 등록해 주세요.
. `meatplatform-sandbox` 을 참여자분의 저장소에 Fork 해 주세요.
. `main` 브랜치를 최신 상태로 업데이트한 후, 작업을 잘 나타내는 새 브랜치를 생성해주세요. 브랜치 이름은 영문 기준으로 작성해 주시기 바랍니다.
. 테스트를 작성해 주세요. link:{link-prj}/tree/main/server[Server] 프로젝트는 `JUnit` 를, link:{link-prj}/tree/main/client[Client] 프로젝트는 `flutter test` 를 기본 테스팅 도구로 활용합니다.
. 작업을 마치시면 commit message 를 아래 형식으로 작성해 주세요. Commit message 는 한국어, 또는 영어로 작성해 주시기 바랍니다.
+
[source,shell]
----
# ?? 는 Github issue 번호입니다.
# Commit message 의 길이는 제목 국/한 혼용 40자, 영문 72자를 넘기지 않도록 작성해 주세요.
# 본문은 제한 없이 자유롭게 작성해 주시기 바랍니다.

$ git commit -m "#1 커뮤니티 가이드 문서 추가"
[master 6009820] #1 커뮤니티 가이드 문서 추가
 2 files changed, 143 insertions(+)
 create mode 100644 CODE_OF_CONDUCT.adoc
 create mode 100644 CONTRIBUTING.adoc
----
. 참여자분의 브랜치에서 `meatplatform-sandbox/main` 브랜치로 새로운 PR 을 만드세요.
. 리뷰를 기다려 주세요. 검토를 거친 후, 병합해 드리겠습니다.
. 참여 감사합니다!

== 병합 규칙
내 Commit 이 사라졌더라도 놀라지 마세요!

참여자 여러분들의 기여 내용은 Github 의 link:https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#squash-and-merge-your-pull-request-commits[Squash and Merge] 규칙에 의거해 병합할 예정입니다. 내용이 궁금하시다면, 확인해 보시기 바랍니다.
